# CS 178 Movie Review Project

##### Note: You might need to run pip install pyarrow and / or pip install fastparquet to access the dataset since its uses a .parquet extension

In [5]:
import pandas as pd

df = pd.read_parquet("../data/train.parquet")
df.head()

                                                text  label
0  I rented I AM CURIOUS-YELLOW from my video sto...      0
1  "I Am Curious: Yellow" is a risible and preten...      0
2  If only to avoid making this type of film in t...      0
3  This film was probably inspired by Godard's Ma...      0
4  Oh, brother...after hearing about this ridicul...      0

In [8]:
print(df.columns)
print()

print(df.info())

Index(['text', 'label'], dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    25000 non-null  object
 1   label   25000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 390.8+ KB
None

In [10]:
#Positive Reviews 
df[df["label"] == 1].head(10)

                                                    text  label
12500  Zentropa has much in common with The Third Man...      1
12501  Zentropa is the most original movie I've seen ...      1
12502  Lars Von Trier is never backward in trying out...      1
12503  *Contains spoilers due to me having to describ...      1
12504  That was the first thing that sprang to mind a...      1
12505  I had started to lose my faith in films of rec...      1
12506  Critics need to review what they class as a qu...      1
12507  It is not every film's job to stimulate you su...      1
12508  The best way for me to describe Europa, which ...      1
12509  Released as Zentropa in North America to avoid...      1

In [11]:
#Negative Reviews
df[df["label"] == 0].head(10)

                                                text  label
0  I rented I AM CURIOUS-YELLOW from my video sto...      0
1  "I Am Curious: Yellow" is a risible and preten...      0
2  If only to avoid making this type of film in t...      0
3  This film was probably inspired by Godard's Ma...      0
4  Oh, brother...after hearing about this ridicul...      0
5  I would put this at the top of my list of film...      0
6  Whoever wrote the screenplay for this movie ob...      0
7  When I first saw a glimpse of this movie, I qu...      0
8  Who are these "They"- the actors? the filmmake...      0
9  This is said to be a personal film for Peter B...      0